/*
 * This source file was generated by the Gradle 'init' task
 */
package java_basics;

public class App {

    public static void main(String[] args) {
        System.out.println("Testing fibonacci method");
        Quest6 q6 = new Quest6();
        System.out.println(q6.fibonacci(5));
    }
}
